#!/bin/bash

INTEGRATION_BRANCH_NAME=integration-branch
BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
NUM_COMMITS=$(git rev-list --left-only --count $INTEGRATION_BRANCH_NAME...$BRANCH_NAME)

if [ $NUM_COMMITS -gt 0 ] 
then
    echo "FAIL: Cannot commit changes. Your branch is behind $INTEGRATION_BRANCH_NAME by $NUM_COMMITS commits"
    exit 1
else
    echo "SUCCESS: You're branch is up to date with $INTEGRATION_BRANCH_NAME"
    exit 0
fi

